version: '3.8'

services:
  db:
    image: postgres:15
    container_name: clearcart-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=clearcart
      - POSTGRES_PASSWORD=clearcart
      - POSTGRES_DB=clearcart
    volumes:
      - clearcart-data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: clearcart-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/clearcart
      - SPRING_DATASOURCE_USERNAME=clearcart
      - SPRING_DATASOURCE_PASSWORD=clearcart
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - ALLOWED_ORIGINS=http://localhost:5173
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8080/graphql
    container_name: clearcart-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped


volumes:
  clearcart-data: