services:
  db:
    image: postgres:15
    container_name: clearcart-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=clearcart
      - POSTGRES_PASSWORD=clearcart
      - POSTGRES_DB=clearcart
    volumes:
      - clearcart-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: clearcart-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/clearcart
      - SPRING_DATASOURCE_USERNAME=clearcart
      - SPRING_DATASOURCE_PASSWORD=clearcart
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate # We tell Hibernate to validate against Flyway's schema, not create its own.
    depends_on:
      - db # Ensures the database starts before the backend

volumes:
  clearcart-data: